# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server_warning(object):
    def setupUi(self, server_warning):
        server_warning.setObjectName("server_warning")
        server_warning.resize(340, 75)
        self.textBrowser = QtWidgets.QTextBrowser(server_warning)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 341, 81))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(server_warning)
        QtCore.QMetaObject.connectSlotsByName(server_warning)

    def retranslateUi(self, server_warning):
        _translate = QtCore.QCoreApplication.translate
        server_warning.setWindowTitle(_translate("server_warning", "Dialog"))
        self.textBrowser.setHtml(_translate("server_warning", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">WARNING:  CONNECTING TO SERVER FAIL</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">       PLEASE CHECK CONNECTION</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    server_warning = QtWidgets.QDialog()
    ui = Ui_server_warning()
    ui.setupUi(server_warning)
    server_warning.show()
    sys.exit(app.exec_())
