# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_warning(object):
    def setupUi(self, warning):
        warning.setObjectName("warning")
        warning.resize(349, 95)
        self.seial_workspace = QtWidgets.QFrame(warning)
        self.seial_workspace.setGeometry(QtCore.QRect(-80, -10, 491, 271))
        self.seial_workspace.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.seial_workspace.setObjectName("seial_workspace")
        self.textBrowser = QtWidgets.QTextBrowser(self.seial_workspace)
        self.textBrowser.setGeometry(QtCore.QRect(90, 20, 331, 81))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(warning)
        QtCore.QMetaObject.connectSlotsByName(warning)

    def retranslateUi(self, warning):
        _translate = QtCore.QCoreApplication.translate
        warning.setWindowTitle(_translate("warning", "Dialog"))
        self.textBrowser.setHtml(_translate("warning", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">WARNING:  COM PORT NOT OPEN</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">       PLEASE CHECK CONNECTION</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    warning = QtWidgets.QDialog()
    ui = Ui_warning()
    ui.setupUi(warning)
    warning.show()
    sys.exit(app.exec_())
